### ISSUE TITLE
the link of project page invalid

### ISSUE THREAD

**Issue by guofengming11-chinese** [sibozhang/Speech2Video#7]
the link of project page invalid

**Comment by michaelzhang-ai** [comment]
It is on google sites. You may need VPN to access it from china. https://sites.google.com/view/sibozhang/speech2video

**Comment by guofengming11** [comment]
> It is on google sites. You may need VPN to access it from china. https://sites.google.com/view/sibozhang/speech2video

请问project链接里面有代码么？ 代码在哪里找呢？
